### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by rahulshamkuwar** [SiGMobileUIUC/OnePlace-Illinois#10]
Setup firebase and connect it to the app. After that set up the database and basic functions. Maybe input some mock data for testing.

**Comment by ashayp22** [comment]
For identifying course: subjectID, subjectNumber, name

**Comment by rahulshamkuwar** [comment]
> For identifying course: subjectID, subjectNumber, name


To clarify, store subjectID, subjectNumber, name, and term from the `CourseListItem` class and the sectionID from `SectionItem`.
