### ISSUE TITLE
Section Page/ Merge with Homework Page

### ISSUE THREAD

**Issue by rahulshamkuwar** [SiGMobileUIUC/OnePlace-Illinois#23]
@AndrewLester Let me know what you think about adding section information to the Homework Page? That way when a user opens the page they see both? Maybe have the section info at the top and then hw stuff below?

**Comment by AndrewLester** [comment]
By section info do you mean course info essentially? I think that's not a bad idea, but it may crowd the homework page. What we can do is, once the course screen is created, have a press on the course name in the homework screen navigate the user to the corresponding course screen. What do you think about that?
