### ISSUE TITLE
Login with OpenID and Shibboleth

### ISSUE THREAD

**Issue by rahulshamkuwar** [SiGMobileUIUC/OnePlace-Illinois#29]

**Comment by jdubpark** [comment]
Look at the Illinois app:
- [https://github.com/rokwire/illinois-app/blob/develop/lib/service/Auth.dart](https://github.com/rokwire/illinois-app/blob/develop/lib/service/Auth.dart)
- [https://github.com/rokwire/illinois-app/blob/develop/lib/model/Auth.dart](https://github.com/rokwire/illinois-app/blob/develop/lib/model/Auth.dart)

It opens up the phone's browser and retrieves the token on completion.
